version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Docker...
      - nohup /usr/local/bin/dockerd-entrypoint.sh &>/tmp/dockerd.log &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Docker is ready.

      - echo Installing kubectl...
      - curl -LO "https://dl.k8s.io/release/v1.29.1/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/
      - kubectl version --client

      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 047719652562.dkr.ecr.us-east-1.amazonaws.com

      - echo Configuring kubeconfig for EKS...
      - aws eks update-kubeconfig --region us-east-1 --name Capstone-cluster

      - echo Installing Sonar Scanner...
      - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner.zip
      - mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
      - export PATH=$PATH:/opt/sonar-scanner/bin
      - echo "export PATH=$PATH:/opt/sonar-scanner/bin" >> ~/.bashrc

  pre_build:
    commands:
      - echo Build started on `date`
      - echo Started Pre Build Steps...

      - echo Fetching container name from SSM...
      - CONTAINER_NAME=$(aws ssm get-parameter --name "/python-app/eks-python-deploy/container-name" --with-decryption --query "Parameter.Value" --output text)
      - echo Fetched container name: $CONTAINER_NAME

      - echo Testing connection to SonarQube server...
      - curl -I http://52.87.101.241 || echo "SonarQube server might be unreachable!"

      - echo Running SonarQube analysis...
      - >
        /opt/sonar-scanner/bin/sonar-scanner
        -Dsonar.projectKey=Capstone_Project
        -Dsonar.sources=.
        -Dsonar.host.url=http://52.87.101.241
        -Dsonar.login=sqp_b25db21244d06591db52eb84baa795ebac8beb80

      - echo Compiling the application...
      - mvn clean package -DskipTests

  build:
    commands:
      - echo Building Docker image...
      - docker build -t capstone_ecr .
      - docker tag capstone_ecr:latest 047719652562.dkr.ecr.us-east-1.amazonaws.com/capstone_ecr:latest

  post_build:
    commands:
      - echo Pushing Docker image to Amazon ECR...
      - docker push 047719652562.dkr.ecr.us-east-1.amazonaws.com/capstone_ecr:latest

      - echo Copying Kubernetes manifest files...
      - mkdir -p k8s-out
      - cp kubernetes/*.yml k8s-out/ || true
      - cp kubernetes/*.yaml k8s-out/ || true
      - ls -l k8s-out

artifacts:
  base-directory: k8s-out
  files:
    - '**/*'
